services:
  db:
    image: postgres:13-alpine3.20
    volumes:
      - db_python:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=tioziio
      - POSTGRES_PASSWORD=tioziio
    ports:
      - "5432:5432"

  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=postgres
      - DB_USER=tioziio
      - DB_PASSWORD=tioziio
    depends_on:
      - db

volumes:
  db_python:
