services:
  db:
    image: postgres:13-alpine3.20
    volumes:
      - db_python:/var/lib/postgresql/data
    env_file:
      - ./dotenv_files/.postgres.env
    ports:
      - "5432:5432"

  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./data/web/static:/data/web/static
      - ./data/web/media:/data/web/media
    command: >
      sh -c "python manage.py collectstatic --noinput &&
              python manage.py makemigrations --noinput &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./dotenv_files/.django.env
    depends_on:
      - db

volumes:
  db_python:
